In [12]:
import pandas as pd
data = pd.read_parquet('/mnt/code/yehangcheng/Intruct_augment/pipline/data/chatling-1204-1214-embedding-decup-random--select-1k-40k.parquet')

In [72]:
data.to_json(
    '/mnt/code/yehangcheng/Intruct_augment/pipline/data/chatling-1204-1214-embedding-decup-random--select-1k-40k-quality-rating-3-5-complex-clarity-rating-8-10-qwen3-32b-awq.jsonl',
    orient="records",
    lines=True,
    force_ascii=False
)

In [ ]:
data.to_json(
    "/mnt/code/yehangcheng/Intruct_augment/pipline/data/chatling-1204-1214-embedding-decup-random--select-1k-40k-quality-rating-3-5-complex-clarity-rating-8-10-qwen3-32b-awq.json",
    orient="records",
    indent=4,
    force_ascii=False
)

In [ ]:
import json
import pandas as pd

FIELDS = [
    "conversations",
    "classify_prompt_most",
    "scene_id",
    "wpai_task_id",
    "scene_name",
    "response",
]

def extract_fields_from_orig(orig):
    try:
        obj = json.loads(orig) if isinstance(orig, str) else {}
    except Exception:
        obj = {}
    return {k: obj.get(k, None) for k in FIELDS}

# 解析并展开成多列
orig_expanded = data["orig"].apply(extract_fields_from_orig).apply(pd.Series)

# 写回 data（如有同名列：例如 group_id，会被 orig 里的覆盖；不想覆盖见下方“避免覆盖”）
data = pd.concat([data.drop(columns=[c for c in orig_expanded.columns if c in data.columns], errors="ignore"),
                  orig_expanded],
                 axis=1)

data

,uid,idx,embedding,orig,source,group_id,quality_rating,complex_clarity_rating,Clarity,Cognitive_Complexity,orig_type,conversations,classify_prompt_most,scene_id,wpai_task_id,scene_name,response
0,a39b70542bab402b92d197df9e8a83c9,18,"[-0.052168217, 0.0030933078, -0.011202791, -0....","{""account"": ""bigdata"", ""type"": ""chatling-plus""...",,9,3.0,"{'Clarity': 8, 'Cognitive_Complexity': 8}",8,8,chatling-plus,"[{'role': 'user', 'content': '## 当前日期 北京时间：20...","{""类别"":""指令遵循任务""}",33,-1,SQL智能助手(bigdata),"{ ""query_rewrite"": ""2025年11月1日到11月7日东南战区一次性计收..."
1,6c1e14bf92d34eab9db76e25187c2f73,108,"[-0.018673785, 0.0063884, -0.015725292, -0.103...","{""account"": ""bigdata"", ""type"": ""deepseek-v3.1-...",,18,6.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8,deepseek-v3.1-doubao,"[{'role': 'user', 'content': 'Your primary goa...","{""类别"":""指令遵循任务""}",33,-1,SQL智能助手(bigdata),"<tool_call>{ ""name"": ""todoWriter"", ""argument..."
2,45eacc3265264f68b7e39d39d689a862,111,"[-0.021912182, 0.00026663052, -0.015416093, -0...","{""account"": ""bigdata"", ""type"": ""deepseek-v3.1-...",,18,7.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8,deepseek-v3.1-doubao,"[{'role': 'user', 'content': 'Your primary goa...","{""类别"":""指令遵循任务""}",33,-1,SQL智能助手(bigdata),"我将继续执行计划，更新任务状态并检查当前结果是否符合要求。<tool_call>{ ""na..."
3,01d860838eb84906b36ab92e578c6bc0,149,"[-0.022308884, -0.0063256794, -0.015452041, -0...","{""account"": ""bigdata"", ""type"": ""deepseek-v3.1-...",,19,5.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8,deepseek-v3.1-doubao,"[{'role': 'user', 'content': 'Your primary goa...","{""类别"":""指令遵循任务""}",41,-1,辅助智能运营和用户洞察分析,"<tool_call>{ ""name"": ""searchXingHeKnowledge"",..."
4,8419f2cb9b684beea8bc07bf84ba09f1,168,"[-0.006608005, -0.039921466, -0.014400894, -0....","{""account"": ""bigdata"", ""type"": ""deepseek-v3.1-...",,20,8.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8,deepseek-v3.1-doubao,"[{'role': 'user', 'content': '# ChatBI 生成 JSON...","{""类别"":""指令遵循任务""}",48,-1,万象智能运营助手,根据用户需求，需要查询孔瑞所在班级信息。高三学生成绩明细图表包含学生姓名和班级字段，可以满足...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2002,b6c662529f27425f9a919452965e8017,367645,"[0.018084485, -0.03403171, -0.012001522, -0.07...","{""account"": ""zhaobing02"", ""type"": ""deepseek-ch...",,289,8.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8,deepseek-chat,"[{'role': 'user', 'content': '{""task_descripti...","{""类别"":""生成性任务""}",226,-1,TEG-多媒体应用部-HBG-房源视频生成,"```json{ ""0"": { ""讲解口播"": ""这套房南北通透，采光特别好，住起来..."
2003,1c840871720a419d8ce2ad5b79077c05,367689,"[-0.014195758, -0.04292527, -0.011322807, -0.0...","{""account"": ""zhaobing02"", ""type"": ""deepseek-ch...",,289,6.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8,deepseek-chat,"[{'role': 'user', 'content': '{""task_descripti...","{""类别"":""生成性任务""}",226,-1,TEG-多媒体应用部-HBG-房源视频生成,"```json{ ""0"": { ""讲解口播"": ""这个客厅采用客餐厅一体的设计，空间..."
2004,cfd49b0a09554374ac1151e7bd43b052,367693,"[-0.03125974, -0.049028434, -0.011434484, -0.0...","{""account"": ""zhaobing02"", ""type"": ""deepseek-ch...",,289,8.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8,deepseek-chat,"[{'role': 'user', 'content': '{""task_descripti...","{""类别"":""生成性任务""}",226,-1,TEG-多媒体应用部-HBG-房源视频生成,"```json{ ""0"": { ""讲解口播"": ""这套房位于万科金域中央，精装三房，..."
2005,d679cedc47ea49ebba0abbcf117e6c8a,428432,"[0.011779036, -0.049406514, -0.011697237, -0.0...","{""account"": ""zhaozhongxin"", ""type"": ""customize...",,301,3.0,"{'Clarity': 10, 'Cognitive_Complexity': 8}",10,8,customized-model,"[{'role': 'system', 'content': 'You are a help...","{""类别"":""指令遵循任务""}",111,19158,TEG-信安-免审-291-商业地产个人发布,是
2006,c3c5dae3c75846b092ced9ebf417db3b,428433,"[0.004493542, -0.05751734, -0.010325586, -0.07...","{""account"": ""zhaozhongxin"", ""type"": ""customize...",,301,3.0,"{'Clarity': 10, 'Cognitive_Complexity': 8}",10,8,customized-model,"[{'role': 'system', 'content': 'You are a help...","{""类别"":""指令遵循任务""}",111,19158,TEG-信安-免审-291-商业地产个人发布,是

In [102]:
data.to_parquet('/mnt/code/yehangcheng/Intruct_augment/pipline/data/chatling-1204-1214-embedding-decup-random--select-1k-40k-quality-rating-3-8-complex-clarity-rating-8-10-qwen3-32b-awq-format.parquet')

In [26]:
import json
import ast

def _strip_code_fence(text: str) -> str:
    if text is None:
        return ""
    text = str(text)
    return text.replace("```json", "").replace("```", "").strip()

def _try_json_loads(s: str):
    # 直接按 JSON 解析
    return json.loads(s)

def _try_ast_literal_eval(s: str):
    # 1) 直接按 Python 字面量解析（常见于单引号、True/False/None）
    try:
        return ast.literal_eval(s)
    except Exception:
        pass

    # 2) 兼容一些“接近 JSON 但不规范”的情况：true/false/null
    #    将其转换成 Python 的 True/False/None 再 literal_eval
    s2 = (
        s.replace(": true", ": True")
         .replace(": false", ": False")
         .replace(": null", ": None")
    )
    return ast.literal_eval(s2)

def extract_score(text):
    s = _strip_code_fence(text)
    if not s:
        return None

    obj = None

    # 方法1：json.loads
    try:
        obj = _try_json_loads(s)
    except Exception:
        # 方法2：ast.literal_eval
        try:
            obj = _try_ast_literal_eval(s)
        except Exception:
            return None

    # 必须是 dict 且包含字段，否则返回 None
    if not isinstance(obj, dict):
        return None

    clarity = obj.get("Clarity", None)
    cog = obj.get("Cognitive_Complexity", None)

    # 两个字段任意一个缺失，也按你需求返回 None（你也可改成只缺一个就保留另一个）
    if clarity is None or cog is None:
        return None

    return {"Clarity": clarity['Score'], "Cognitive_Complexity": cog['Score']}

data["complex_clarity_rating"] = data["sglang_result"].apply(extract_score)

In [31]:
import pandas as pd

# 1. 先确保 complex_clarity_rating 是 dict
mask_valid = data["complex_clarity_rating"].apply(lambda x: isinstance(x, dict))

df = data[mask_valid].copy()

# 2. 拆出 Clarity 和 Cognitive_Complexity
df["Clarity"] = df["complex_clarity_rating"].apply(lambda x: x.get("Clarity"))
df["Cognitive_Complexity"] = df["complex_clarity_rating"].apply(lambda x: x.get("Cognitive_Complexity"))

# 3. 条件过滤
filtered_df = df[
    (df["quality_rating"].between(3, 8)) &
    (df["Clarity"].between(8, 10)) &
    (df["Cognitive_Complexity"].between(8, 10))
]

filtered_df

,uid,idx,embedding,orig,source,group_id,quality_rating,complex_clarity_rating,Clarity,Cognitive_Complexity
14,a39b70542bab402b92d197df9e8a83c9,18,"[-0.052168217, 0.0030933078, -0.011202791, -0....","{""account"": ""bigdata"", ""type"": ""chatling-plus""...",,9,3.0,"{'Clarity': 8, 'Cognitive_Complexity': 8}",8,8
61,6c1e14bf92d34eab9db76e25187c2f73,108,"[-0.018673785, 0.0063884, -0.015725292, -0.103...","{""account"": ""bigdata"", ""type"": ""deepseek-v3.1-...",,18,6.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8
64,45eacc3265264f68b7e39d39d689a862,111,"[-0.021912182, 0.00026663052, -0.015416093, -0...","{""account"": ""bigdata"", ""type"": ""deepseek-v3.1-...",,18,7.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8
85,01d860838eb84906b36ab92e578c6bc0,149,"[-0.022308884, -0.0063256794, -0.015452041, -0...","{""account"": ""bigdata"", ""type"": ""deepseek-v3.1-...",,19,5.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8
96,8419f2cb9b684beea8bc07bf84ba09f1,168,"[-0.006608005, -0.039921466, -0.014400894, -0....","{""account"": ""bigdata"", ""type"": ""deepseek-v3.1-...",,20,8.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8
...,...,...,...,...,...,...,...,...,...,...
38572,b6c662529f27425f9a919452965e8017,367645,"[0.018084485, -0.03403171, -0.012001522, -0.07...","{""account"": ""zhaobing02"", ""type"": ""deepseek-ch...",,289,8.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8
38580,1c840871720a419d8ce2ad5b79077c05,367689,"[-0.014195758, -0.04292527, -0.011322807, -0.0...","{""account"": ""zhaobing02"", ""type"": ""deepseek-ch...",,289,6.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8
38582,cfd49b0a09554374ac1151e7bd43b052,367693,"[-0.03125974, -0.049028434, -0.011434484, -0.0...","{""account"": ""zhaobing02"", ""type"": ""deepseek-ch...",,289,8.0,"{'Clarity': 9, 'Cognitive_Complexity': 8}",9,8
40395,d679cedc47ea49ebba0abbcf117e6c8a,428432,"[0.011779036, -0.049406514, -0.011697237, -0.0...","{""account"": ""zhaozhongxin"", ""type"": ""customize...",,301,3.0,"{'Clarity': 10, 'Cognitive_Complexity': 8}",10,8
40396,c3c5dae3c75846b092ced9ebf417db3b,428433,"[0.004493542, -0.05751734, -0.010325586, -0.07...","{""account"": ""zhaozhongxin"", ""type"": ""customize...",,301,3.0,"{'Clarity': 10, 'Cognitive_Complexity': 8}",10,8

In [43]:
filtered_df.to_parquet('/mnt/code/yehangcheng/Intruct_augment/pipline/data/chatling-1204-1214-embedding-decup-random--select-1k-40k-quality-rating-3-5-complex-clarity-rating-8-10-qwen3-32b-awq.parquet',index=False)

In [40]:
filtered_df['orig'][40395]

'{"account": "zhaozhongxin", "type": "customized-model", "question": "[LlmMessage(role=user, content=<|im_start|>systemYou are a helpful assistant.<|im_end|><|im_start|>user# 角色你是一位严谨的信息管控智能助手，专门负责审核房东发布的房源帖子。你将根据严格的审核规则检查帖子的标题和内容，确保其符合平台规定。## 技能### 技能一：信息审核- **审核内容**：【帖子标题】：急转！大学城最大食堂档口 稳定学生客源 接手即营业【帖子内容1】:西安市长安区，培华学院，在校生两万余人。店铺位于学校最大的餐厅——沁园餐厅二楼电梯口第一家。本店属于六年老店，由于家中有事含泪转让。沁园餐厅人流量大，客源稳定，学生消费能力高，生意火爆。学校免费提供后厨基础设备，免费提供桌椅板凳，锅碗瓢盆，水、电、天然气，餐厅干净明亮，简约装修，专人打扫卫生。学校为半封闭管理，学生在校时间长，有意向的朋友可到校实地考察，现在想找学校档口的人比较多，像本店这种好位置的铺面很少，资源紧张，有需要的抓紧时间哦！【帖子内容2】:未提供- **审核标准**：  - 联系方式：禁止询问或公开联系方式，避免使用“微信同号”、“加微信”以及类似隐含联系方式的内容，如“幺三6131幺3759”，或引导关注公众号。  - 广告法规合规：禁止违反广告法规的内容，如夸大宣传、虚假承诺和误导性信息。  - 极限词使用：禁止使用带有绝对性或唯一性的词语，如“最”、“极”、“唯一”、“绝对”、“首选”、“最低”、“最集中”、“最佳”、“最优”等。  - 政治相关：禁止涉及政治敏感内容，包括但不限于“文化大革命”等政治相关话题。  - 歧视性言论：禁止种族、性别、宗教、国籍、年龄等方面的歧视性言论。  - 违法违规活动：禁止发布违法或不合规的内容。  - 淫秽色情：禁止介绍或推荐淫秽色情网站、论坛、场所等内容。  - 标题和内容规范：    1.禁止标题包含纯广告内容，如“走过路过不要错过”、“挥泪大甩卖”等。    2.禁止发布仅包含融资、贷款、公积金提取等信息的房源描述。    3.禁止提供消除贷款不良记录、拆借贷款等信息。    4.禁止使用“零首付”、“首付分期付”等宣传内容。    5.禁止出现其他平台名称，如“百姓网”、“搜房”等。  - 无意义信息：禁止仅包含数字、字母、乱码或无中文的内容。  - 业务合规：禁止发布“出售小产权房”、“回本快”等违反广告法的内容。  - 效果和未来预期：禁止快速回本、轻松获利的描述，例如“接手即赚”、“接手可盈利”、“月收入可观”等。### 技能二：输出结果- **通过审核**：如果帖子标题和内容均符合审核标准，输出“是”。- **未通过审核**：如果帖子标题或内容不符合审核标准，输出“否”。## 限制- **严格遵守审核标准**：在审核过程中，必须严格按照审核标准进行判断，不得主观臆断。- **保持中立客观**：在审核过程中，必须保持中立客观，不得带有个人情感或偏见。- **仅输出“是”或“否”**：审核结果只能输出“是”或“否”，不得添加其他说明或评论。<|im_end|><|im_start|>assistant, tool_call_id=null, tool_calls=null)]", "response": "是", "scene_name": "TEG-信安-免审-291-商业地产个人发布", "scene_id": 111, "wpai_task_id": 19158, "group_id": 301, "classify_prompt_most": "{\\"类别\\":\\"指令遵循任务\\"}", "conversations": [{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": "# 角色你是一位严谨的信息管控智能助手，专门负责审核房东发布的房源帖子。你将根据严格的审核规则检查帖子的标题和内容，确保其符合平台规定。## 技能### 技能一：信息审核- **审核内容**：【帖子标题】：急转！大学城最大食堂档口 稳定学生客源 接手即营业【帖子内容1】:西安市长安区，培华学院，在校生两万余人。店铺位于学校最大的餐厅——沁园餐厅二楼电梯口第一家。本店属于六年老店，由于家中有事含泪转让。沁园餐厅人流量大，客源稳定，学生消费能力高，生意火爆。学校免费提供后厨基础设备，免费提供桌椅板凳，锅碗瓢盆，水、电、天然气，餐厅干净明亮，简约装修，专人打扫卫生。学校为半封闭管理，学生在校时间长，有意向的朋友可到校实地考察，现在想找学校档口的人比较多，像本店这种好位置的铺面很少，资源紧张，有需要的抓紧时间哦！【帖子内容2】:未提供- **审核标准**：  - 联系方式：禁止询问或公开联系方式，避免使用“微信同号”、“加微信”以及类似隐含联系方式的内容，如“幺三6131幺3759”，或引导关注公众号。  - 广告法规合规：禁止违反广告法规的内容，如夸大宣传、虚假承诺和误导性信息。  - 极限词使用：禁止使用带有绝对性或唯一性的词语，如“最”、“极”、“唯一”、“绝对”、“首选”、“最低”、“最集中”、“最佳”、“最优”等。  - 政治相关：禁止涉及政治敏感内容，包括但不限于“文化大革命”等政治相关话题。  - 歧视性言论：禁止种族、性别、宗教、国籍、年龄等方面的歧视性言论。  - 违法违规活动：禁止发布违法或不合规的内容。  - 淫秽色情：禁止介绍或推荐淫秽色情网站、论坛、场所等内容。  - 标题和内容规范：    1.禁止标题包含纯广告内容，如“走过路过不要错过”、“挥泪大甩卖”等。    2.禁止发布仅包含融资、贷款、公积金提取等信息的房源描述。    3.禁止提供消除贷款不良记录、拆借贷款等信息。    4.禁止使用“零首付”、“首付分期付”等宣传内容。    5.禁止出现其他平台名称，如“百姓网”、“搜房”等。  - 无意义信息：禁止仅包含数字、字母、乱码或无中文的内容。  - 业务合规：禁止发布“出售小产权房”、“回本快”等违反广告法的内容。  - 效果和未来预期：禁止快速回本、轻松获利的描述，例如“接手即赚”、“接手可盈利”、“月收入可观”等。### 技能二：输出结果- **通过审核**：如果帖子标题和内容均符合审核标准，输出“是”。- **未通过审核**：如果帖子标题或内容不符合审核标准，输出“否”。## 限制- **严格遵守审核标准**：在审核过程中，必须严格按照审核标准进行判断，不得主观臆断。- **保持中立客观**：在审核过程中，必须保持中立客观，不得带有个人情感或偏见。- **仅输出“是”或“否”**：审核结果只能输出“是”或“否”，不得添加其他说明或评论。"}]}'

In [41]:
import json

def get_type(orig):
    try:
        return json.loads(orig).get("type")
    except Exception:
        return None

# 提取 type
filtered_df["orig_type"] = filtered_df["orig"].apply(get_type)

# 统计 type == "customized-model" 的数量
count_customized = (filtered_df["orig_type"] == "customized-model").sum()

count_customized

/tmp/ipykernel_456184/614382417.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["orig_type"] = filtered_df["orig"].apply(get_type)

np.int64(891)

In [29]:
data = data.drop(columns='sglang_result')

In [56]:
filtered_df.to_csv('/mnt/code/yehangcheng/Intruct_augment/pipline/data/chatling-1204-1214-embedding-decup-random--select-1k-40k-quality-rating-3-5-complex-clarity-rating-8-10-qwen3-32b-awq.csv',index=False)

In [53]:
import re
import pandas as pd
import numpy as np
pattern = re.compile(r"\[\[\s*([+-]?\d+(?:\.\d+)?)\s*\]\]")

def extract_score(text):
    if not isinstance(text, str):
        return None
    m = pattern.search(text)
    return float(m.group(1)) if m else None

data["quality_rating"] = data["sglang_result"].apply(extract_score)


# bins = list(range(0, 12))  # [0,1), [1,2), ..., [10,11)
# labels = [f"{i}-{i+1}" for i in range(0, 11)]
# df = data.copy()

# df["rating_bin"] = pd.cut(
#     df["quality_rating"],
#     bins=bins,
#     labels=labels,
#     right=False,
#     include_lowest=True
# )
# dist_count = (
#     df
#     .groupby(["group_id", "rating_bin"])
#     .size()
#     .unstack(fill_value=0)
#     .sort_index()
# )

In [6]:
import json
import pandas as pd
import numpy as np

def load_parquet(path):
    return pd.read_parquet(path)

def load_jsonl(path):
    with open(path,"r") as f:
        data = [json.loads(line) for line in f]
    return data
    
def load_json(path):
    with open(path, "r") as f:
        data = json.load(f)
    return data

def save_json(data, path):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

def save_jsonl(data, path):
    with open(path, 'w', encoding='utf-8') as f:
        for line in data:
            json_line = json.dumps(line, ensure_ascii=False)
            f.write(json_line + '\n')

def save_result(result, save_path):
    with open(save_path, 'a') as f:
        json.dump(result, f, ensure_ascii=False)
        f.write('\n')
        
def load_json_or_jsonl(file_path):
    try:
        with open(file_path, 'r') as f:
            return_data = json.load(f)
    except:
        with open(file_path, 'r') as f:
            data = f.readlines()
        return_data = []
        for i in range(len(data)):
            try:
                return_data.append(json.loads(data[i]))
            except:
                # print(data[i])
                continue
    return return_data

In [7]:
data = load_json_or_jsonl('/opt/users/ye/data/core_data/filter_all_over_8_to_10_168w_concat_rw_lb_if_leetcode_zh_202w.jsonl')